# Generated by Django 6.0.3 on 2026-03-21 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_teacher_subjects_teacher_teacher_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_id', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=128)),
            ],
        ),
    ]
