# Generated by Django 6.0.3 on 2026-03-22 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_classsection'),
    ]

    operations = [
        migrations.AddField(
            model_name='classsection',
            name='grade',
            field=models.ManyToManyField(blank=True, to='portal.grade'),
        ),
    ]
