# Generated by Django 6.0.3 on 2026-03-22 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0007_rename_grade_classsection_grades'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='department',
        ),
    ]
