# Generated by Django 6.0.3 on 2026-03-22 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_classsection_grade'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classsection',
            old_name='grade',
            new_name='grades',
        ),
    ]
