# Generated by Django 6.0.3 on 2026-03-22 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0009_subject_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classsection',
            name='grades',
        ),
        migrations.AddField(
            model_name='grade',
            name='section',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='portal.classsection'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='grade',
            unique_together={('student', 'subject', 'semester', 'school_yr')},
        ),
    ]
