# Generated by Django 6.0.3 on 2026-03-30 08:21

import portal.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0010_remove_classsection_grades_grade_section_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sy', models.CharField(default=portal.models.current_school_year, max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(choices=[('1st', '1st Semester'), ('2nd', '2nd Semester')], default='1st', max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='classsection',
            name='school_yr',
            field=models.CharField(default='2026 - 2027', max_length=20),
        ),
        migrations.AlterField(
            model_name='grade',
            name='school_yr',
            field=models.CharField(default='2026 - 2027', max_length=20),
        ),
    ]
