# Generated by Django 6.0.3 on 2026-03-30 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0011_schoolyear_semester_alter_classsection_school_yr_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schoolyear',
            name='sy',
        ),
        migrations.RemoveField(
            model_name='semester',
            name='semester',
        ),
    ]
