# Generated by Django 6.0.3 on 2026-03-30 08:41

import portal.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0012_remove_schoolyear_sy_remove_semester_semester'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolyear',
            name='sy',
            field=models.CharField(default=portal.models.current_school_year, max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='semester',
            name='semester',
            field=models.CharField(choices=[('1st', '1st Semester'), ('2nd', '2nd Semester')], default='1st', max_length=5),
        ),
        migrations.AlterField(
            model_name='classsection',
            name='school_yr',
            field=models.CharField(default='2026-2027', max_length=20),
        ),
        migrations.AlterField(
            model_name='grade',
            name='school_yr',
            field=models.CharField(default='2026-2027', max_length=20),
        ),
    ]
