# Generated by Django 6.0.3 on 2026-04-03 07:13

import portal.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0013_schoolyear_sy_semester_semester_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classsection',
            name='school_yr',
            field=models.CharField(default=portal.models.current_school_year, max_length=20),
        ),
        migrations.AlterField(
            model_name='grade',
            name='school_yr',
            field=models.CharField(default=portal.models.current_school_year, max_length=20),
        ),
    ]
