# Generated by Django 6.0.3 on 2026-04-10 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0014_alter_classsection_school_yr_alter_grade_school_yr'),
    ]

    operations = [
        migrations.AddField(
            model_name='classsection',
            name='admin_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(blank=True, max_length=254, unique=True),
        ),
    ]
