# Generated by Django 6.0.3 on 2026-04-10 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0015_classsection_admin_approved_alter_student_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='classsection',
            name='submitted',
            field=models.BooleanField(default=False),
        ),
    ]
