
from . import views
from django.urls import path


urlpatterns = [
    path('', views.index),
    path('', views.index, name='index'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('register/', views.register_view, name='register'),
    path('grades/', views.grades_view, name='grades'),
    path('profile/<int:pk>/', views.profile_view, name='profile'),
    path('teacher/', views.teacher_view, name='teacher'),
    path('teacher/submit/<str:section_id>', views.teacher_submit, name='teacher_submit'),
    path('teacher/login/', views.teacher_login, name='teacher_login'),
    path('teacher/add-grade/', views.teacher_add_grade, name='teacher_add_grade'),
    path('teacher/create-section/', views.teacher_create_section, name='teacher_create_section'),
    path('teacher/section/<int:section_id>/delete/', views.delete_section, name='delete_section'),
    path('teacher/section/remove/<int:section_id>/<str:student_no>/', views.section_remove_student, name='removestudent'),
    path('section/<int:section_id>/bulk-add-students/', views.bulk_add_students, name='bulk_add_students'),
    path('section/<int:section_id>/add-student/', views.add_student_to_section, name='add_student_to_section'),
    path('section/<str:section_name>/<str:subject_code>/<str:semester>/<str:school_yr>/', views.section_view,name='section_view'),
    path('admin/add-teacher/', views.admin_add_teacher, name='admin_add_teacher'),
    path('admin/teachers/', views.admin_teachers, name='admin_teachers'),
    path('admin/students/', views.admin_students, name='admin_students'),
    path('admin/teachers/<int:teacher_id>/delete/', views.delete_teacher, name='delete_teacher'),
    path('admin/teacher/submitted/', views.admin_submitted, name='admin_submitted'),
    path('admin/subjects/', views.admin_subjects, name='admin_subjects'),
    path('admin/add-subject/', views.admin_add_subject, name='admin_add_subject'),
    path('admin/subjects/<int:subject_id>/delete/', views.delete_subject, name='delete_subject'),
    path('admin/students/<int:student_id>/delete/', views.delete_student, name='delete_student'),
    path('admin/login/', views.admin_login, name='admin_login'),
    path('admin/panel/', views.admin_panel, name='admin_panel'),
    path('admin/add-student/', views.admin_add_student, name='admin_add_student'),
    path('admin/bulk-import-students/', views.bulk_import_students, name='bulk_import_students'),
    path('admin/submitted/', views.admin_submitted, name='admin_submitted'),
    path('admin/section_view/<int:section_id>/', views.admin_section_view, name='admin_section_view'),
    path('contact/', views.contact_view, name='contact'),
]